spring.application.name=JobBoardingApplication
spring.mongodb.uri=mongodb+srv://<db_username>:<db_password>@orekiprojects.a3injjq.mongodb.net/?appName=OrekiProjects
spring.mongodb.database=jobPlatform